[evidence]
site_url = "https://sasha-gonch.github.io/CSCI40/"
archive_url = "https://web.archive.org/save/https://sasha-gonch.github.io/CSCI40/index.html"
backlink_urls = [
  "https://sasha-gonch.github.io/CSCI40/cat.html",
  "https://sasha-gonch.github.io/CSCI40/leonberger.html",
]